### PR TITLE
Create workflow.yml

### PR DESCRIPTION
**Pull request by bostick**

### CODE REVIEW

**Comment by kenkangxgwe** [comment]
It will be great if you can provide the secrets to the actions so we may know whether it works or not.

**Comment by kenkangxgwe** [comment]
I think you can directly re-run the action in the webpage somewhere without making a new commit to trigger it.

**Comment by cc-wr** [comment]
@bostick, with respect to 1296e0f, I do not think the `-activate` option for `wolframscript` can take a value even though its help message says otherwise.

**Comment by bostick** [comment]
@kenkangxgwe Where would that be? I did not know about that

**Comment by bostick** [comment]
@cc-wr Do you have an example of what a succesfull script for authenticating and activating looks like?

**Comment by kenkangxgwe** [comment]
Only for failed actions: https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run

**Comment by kenkangxgwe** [comment]
Btw, the original `—activate` worked for me

**Comment by bostick** [comment]
When you say the original -activate worked for you, I wonder what the precise sequence of steps was and how they are different than what the script is doing here. You can see in this run with the original -activate that it failed:
https://github.com/WolframResearch/codeparser/runs/667036479?check_suite_focus=true

**Comment by kenkangxgwe** [comment]
It did not work because at that time you didn’t add the SECRETS. It worked on my fork with my SECRETS: https://github.com/kenkangxgwe/codeparser/runs/666237583?check_suite_focus=true at that step.

**Comment by kenkangxgwe** [comment]
Aha, do you have a valid Wolfram Engine license bound to your account?

**Comment by bostick** [comment]
Yes! That was the problem! I got the license setup, now the engine is working.

Running the tests should be comparatively easy...

**Comment by szhorvat** [comment]
I have never used GitHub Actions before. How exactly will this work when it's set up to run tests?

 1. Will the Wolfram Engine be re-installed every time the tests are run?
 2. Would that cause a problem with the license (we get only two licenses, as I understand)?

**Comment by szhorvat** [comment]
I also want to say thank you to both for trying to get this working! I wanted this for a long time, but I would never have gotten it set up alone.

**Comment by bostick** [comment]
For now, yes, will be re-installed each time. Will figure out a better solution if it causes problems.

Not sure about licensing. But the account that is being used for builds was created for this purpose, and hopefully will be able to accommodate whatever demands there are.

**Pull request merged**
