### PR TITLE
document SourceConvention option and add examples for it

### PR DESCRIPTION
**Pull request by arnoudbuzing**

### CODE REVIEW

**Comment by arnoudbuzing** [comment]
Based on information from #9 and #10

**Comment by bostick** [comment]
@arnoudbuzing `SourceConvention` is now a symbol in `` CodeParser` `` context, so this PR can be revisted.

**Comment by arnoudbuzing** [comment]
Not sure what to do here? This can be merged?

**Comment by bostick** [comment]
The button still links to `Global/ref/SourceConvention`, but `SourceConvention` is in the `` CodeParser` `` context.

**Comment by bostick** [comment]
Closing from inactivity

**Pull request closed without merging**
